// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUIpCl08babohddyu_x3APvV17R4r3rs',
    appId: '1:976149991647:web:9807f4e47ab04b3304d96a',
    messagingSenderId: '976149991647',
    projectId: 'cufoodx',
    authDomain: 'cufoodx.firebaseapp.com',
    storageBucket: 'cufoodx.appspot.com',
    measurementId: 'G-HRKC9JGNFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPItVh499em_GozSFj2xTTJPuaeH-Z2Q',
    appId: '1:976149991647:android:c33bb91287a2169904d96a',
    messagingSenderId: '976149991647',
    projectId: 'cufoodx',
    storageBucket: 'cufoodx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLvvze0YyICffvIo1oTjt7WCKm4xbz7cQ',
    appId: '1:976149991647:ios:bb8cab06476e85dd04d96a',
    messagingSenderId: '976149991647',
    projectId: 'cufoodx',
    storageBucket: 'cufoodx.appspot.com',
    iosClientId: '976149991647-kgee1bhfah4579g68fqsv5r795hnpc81.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuFoods',
  );
}
